name = "MyLeanProjects"
version = "0.1.0"
defaultTargets = ["myleanprojects"]

[leanOptions]
warningAsError = true
autoImplicit = false  # 这是一个常用的严格模式选项


[[lean_lib]]
name = "MyLeanProjects"

[[lean_exe]]
name = "myleanprojects"
root = "Main"
